eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 1111
spring:
  application:
    name: hbu-live-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/live?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

    ############# customer configurations #############
    # json web token
jwt:
    secret: 123456